//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movies.Desktop.CountriesServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Country : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CountriesServiceReference.CountriesServiceSoap")]
    public interface CountriesServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllCountriesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCountries", ReplyAction="*")]
        Movies.Desktop.CountriesServiceReference.GetAllCountriesResponse GetAllCountries(Movies.Desktop.CountriesServiceReference.GetAllCountriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCountries", ReplyAction="*")]
        System.Threading.Tasks.Task<Movies.Desktop.CountriesServiceReference.GetAllCountriesResponse> GetAllCountriesAsync(Movies.Desktop.CountriesServiceReference.GetAllCountriesRequest request);
        
        // CODEGEN: Generating message contract since element name GetCountryResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountry", ReplyAction="*")]
        Movies.Desktop.CountriesServiceReference.GetCountryResponse GetCountry(Movies.Desktop.CountriesServiceReference.GetCountryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountry", ReplyAction="*")]
        System.Threading.Tasks.Task<Movies.Desktop.CountriesServiceReference.GetCountryResponse> GetCountryAsync(Movies.Desktop.CountriesServiceReference.GetCountryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCountriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCountries", Namespace="http://tempuri.org/", Order=0)]
        public Movies.Desktop.CountriesServiceReference.GetAllCountriesRequestBody Body;
        
        public GetAllCountriesRequest() {
        }
        
        public GetAllCountriesRequest(Movies.Desktop.CountriesServiceReference.GetAllCountriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllCountriesRequestBody {
        
        public GetAllCountriesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCountriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCountriesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Movies.Desktop.CountriesServiceReference.GetAllCountriesResponseBody Body;
        
        public GetAllCountriesResponse() {
        }
        
        public GetAllCountriesResponse(Movies.Desktop.CountriesServiceReference.GetAllCountriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllCountriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Movies.Desktop.CountriesServiceReference.Country[] GetAllCountriesResult;
        
        public GetAllCountriesResponseBody() {
        }
        
        public GetAllCountriesResponseBody(Movies.Desktop.CountriesServiceReference.Country[] GetAllCountriesResult) {
            this.GetAllCountriesResult = GetAllCountriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountry", Namespace="http://tempuri.org/", Order=0)]
        public Movies.Desktop.CountriesServiceReference.GetCountryRequestBody Body;
        
        public GetCountryRequest() {
        }
        
        public GetCountryRequest(Movies.Desktop.CountriesServiceReference.GetCountryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetCountryRequestBody() {
        }
        
        public GetCountryRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountryResponse", Namespace="http://tempuri.org/", Order=0)]
        public Movies.Desktop.CountriesServiceReference.GetCountryResponseBody Body;
        
        public GetCountryResponse() {
        }
        
        public GetCountryResponse(Movies.Desktop.CountriesServiceReference.GetCountryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Movies.Desktop.CountriesServiceReference.Country GetCountryResult;
        
        public GetCountryResponseBody() {
        }
        
        public GetCountryResponseBody(Movies.Desktop.CountriesServiceReference.Country GetCountryResult) {
            this.GetCountryResult = GetCountryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CountriesServiceSoapChannel : Movies.Desktop.CountriesServiceReference.CountriesServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CountriesServiceSoapClient : System.ServiceModel.ClientBase<Movies.Desktop.CountriesServiceReference.CountriesServiceSoap>, Movies.Desktop.CountriesServiceReference.CountriesServiceSoap {
        
        public CountriesServiceSoapClient() {
        }
        
        public CountriesServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CountriesServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CountriesServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CountriesServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Movies.Desktop.CountriesServiceReference.GetAllCountriesResponse Movies.Desktop.CountriesServiceReference.CountriesServiceSoap.GetAllCountries(Movies.Desktop.CountriesServiceReference.GetAllCountriesRequest request) {
            return base.Channel.GetAllCountries(request);
        }
        
        public Movies.Desktop.CountriesServiceReference.Country[] GetAllCountries() {
            Movies.Desktop.CountriesServiceReference.GetAllCountriesRequest inValue = new Movies.Desktop.CountriesServiceReference.GetAllCountriesRequest();
            inValue.Body = new Movies.Desktop.CountriesServiceReference.GetAllCountriesRequestBody();
            Movies.Desktop.CountriesServiceReference.GetAllCountriesResponse retVal = ((Movies.Desktop.CountriesServiceReference.CountriesServiceSoap)(this)).GetAllCountries(inValue);
            return retVal.Body.GetAllCountriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Movies.Desktop.CountriesServiceReference.GetAllCountriesResponse> Movies.Desktop.CountriesServiceReference.CountriesServiceSoap.GetAllCountriesAsync(Movies.Desktop.CountriesServiceReference.GetAllCountriesRequest request) {
            return base.Channel.GetAllCountriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Movies.Desktop.CountriesServiceReference.GetAllCountriesResponse> GetAllCountriesAsync() {
            Movies.Desktop.CountriesServiceReference.GetAllCountriesRequest inValue = new Movies.Desktop.CountriesServiceReference.GetAllCountriesRequest();
            inValue.Body = new Movies.Desktop.CountriesServiceReference.GetAllCountriesRequestBody();
            return ((Movies.Desktop.CountriesServiceReference.CountriesServiceSoap)(this)).GetAllCountriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Movies.Desktop.CountriesServiceReference.GetCountryResponse Movies.Desktop.CountriesServiceReference.CountriesServiceSoap.GetCountry(Movies.Desktop.CountriesServiceReference.GetCountryRequest request) {
            return base.Channel.GetCountry(request);
        }
        
        public Movies.Desktop.CountriesServiceReference.Country GetCountry(int id) {
            Movies.Desktop.CountriesServiceReference.GetCountryRequest inValue = new Movies.Desktop.CountriesServiceReference.GetCountryRequest();
            inValue.Body = new Movies.Desktop.CountriesServiceReference.GetCountryRequestBody();
            inValue.Body.id = id;
            Movies.Desktop.CountriesServiceReference.GetCountryResponse retVal = ((Movies.Desktop.CountriesServiceReference.CountriesServiceSoap)(this)).GetCountry(inValue);
            return retVal.Body.GetCountryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Movies.Desktop.CountriesServiceReference.GetCountryResponse> Movies.Desktop.CountriesServiceReference.CountriesServiceSoap.GetCountryAsync(Movies.Desktop.CountriesServiceReference.GetCountryRequest request) {
            return base.Channel.GetCountryAsync(request);
        }
        
        public System.Threading.Tasks.Task<Movies.Desktop.CountriesServiceReference.GetCountryResponse> GetCountryAsync(int id) {
            Movies.Desktop.CountriesServiceReference.GetCountryRequest inValue = new Movies.Desktop.CountriesServiceReference.GetCountryRequest();
            inValue.Body = new Movies.Desktop.CountriesServiceReference.GetCountryRequestBody();
            inValue.Body.id = id;
            return ((Movies.Desktop.CountriesServiceReference.CountriesServiceSoap)(this)).GetCountryAsync(inValue);
        }
    }
}
