//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movies.Desktop.PeopleServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PeopleServiceReference.PeopleServiceSoap")]
    public interface PeopleServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetAllPeopleResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPeople", ReplyAction="*")]
        Movies.Desktop.PeopleServiceReference.GetAllPeopleResponse GetAllPeople(Movies.Desktop.PeopleServiceReference.GetAllPeopleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPeople", ReplyAction="*")]
        System.Threading.Tasks.Task<Movies.Desktop.PeopleServiceReference.GetAllPeopleResponse> GetAllPeopleAsync(Movies.Desktop.PeopleServiceReference.GetAllPeopleRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetPersonResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPerson", ReplyAction="*")]
        Movies.Desktop.PeopleServiceReference.GetPersonResponse GetPerson(Movies.Desktop.PeopleServiceReference.GetPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPerson", ReplyAction="*")]
        System.Threading.Tasks.Task<Movies.Desktop.PeopleServiceReference.GetPersonResponse> GetPersonAsync(Movies.Desktop.PeopleServiceReference.GetPersonRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento person del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertPerson", ReplyAction="*")]
        Movies.Desktop.PeopleServiceReference.InsertPersonResponse InsertPerson(Movies.Desktop.PeopleServiceReference.InsertPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertPerson", ReplyAction="*")]
        System.Threading.Tasks.Task<Movies.Desktop.PeopleServiceReference.InsertPersonResponse> InsertPersonAsync(Movies.Desktop.PeopleServiceReference.InsertPersonRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPeopleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPeople", Namespace="http://tempuri.org/", Order=0)]
        public Movies.Desktop.PeopleServiceReference.GetAllPeopleRequestBody Body;
        
        public GetAllPeopleRequest() {
        }
        
        public GetAllPeopleRequest(Movies.Desktop.PeopleServiceReference.GetAllPeopleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllPeopleRequestBody {
        
        public GetAllPeopleRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPeopleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPeopleResponse", Namespace="http://tempuri.org/", Order=0)]
        public Movies.Desktop.PeopleServiceReference.GetAllPeopleResponseBody Body;
        
        public GetAllPeopleResponse() {
        }
        
        public GetAllPeopleResponse(Movies.Desktop.PeopleServiceReference.GetAllPeopleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllPeopleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Movies.Desktop.PeopleServiceReference.Person[] GetAllPeopleResult;
        
        public GetAllPeopleResponseBody() {
        }
        
        public GetAllPeopleResponseBody(Movies.Desktop.PeopleServiceReference.Person[] GetAllPeopleResult) {
            this.GetAllPeopleResult = GetAllPeopleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPerson", Namespace="http://tempuri.org/", Order=0)]
        public Movies.Desktop.PeopleServiceReference.GetPersonRequestBody Body;
        
        public GetPersonRequest() {
        }
        
        public GetPersonRequest(Movies.Desktop.PeopleServiceReference.GetPersonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPersonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid id;
        
        public GetPersonRequestBody() {
        }
        
        public GetPersonRequestBody(System.Guid id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonResponse", Namespace="http://tempuri.org/", Order=0)]
        public Movies.Desktop.PeopleServiceReference.GetPersonResponseBody Body;
        
        public GetPersonResponse() {
        }
        
        public GetPersonResponse(Movies.Desktop.PeopleServiceReference.GetPersonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPersonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Movies.Desktop.PeopleServiceReference.Person GetPersonResult;
        
        public GetPersonResponseBody() {
        }
        
        public GetPersonResponseBody(Movies.Desktop.PeopleServiceReference.Person GetPersonResult) {
            this.GetPersonResult = GetPersonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertPersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertPerson", Namespace="http://tempuri.org/", Order=0)]
        public Movies.Desktop.PeopleServiceReference.InsertPersonRequestBody Body;
        
        public InsertPersonRequest() {
        }
        
        public InsertPersonRequest(Movies.Desktop.PeopleServiceReference.InsertPersonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertPersonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Movies.Desktop.PeopleServiceReference.Person person;
        
        public InsertPersonRequestBody() {
        }
        
        public InsertPersonRequestBody(Movies.Desktop.PeopleServiceReference.Person person) {
            this.person = person;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertPersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertPersonResponse", Namespace="http://tempuri.org/", Order=0)]
        public Movies.Desktop.PeopleServiceReference.InsertPersonResponseBody Body;
        
        public InsertPersonResponse() {
        }
        
        public InsertPersonResponse(Movies.Desktop.PeopleServiceReference.InsertPersonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertPersonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertPersonResult;
        
        public InsertPersonResponseBody() {
        }
        
        public InsertPersonResponseBody(bool InsertPersonResult) {
            this.InsertPersonResult = InsertPersonResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PeopleServiceSoapChannel : Movies.Desktop.PeopleServiceReference.PeopleServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PeopleServiceSoapClient : System.ServiceModel.ClientBase<Movies.Desktop.PeopleServiceReference.PeopleServiceSoap>, Movies.Desktop.PeopleServiceReference.PeopleServiceSoap {
        
        public PeopleServiceSoapClient() {
        }
        
        public PeopleServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PeopleServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeopleServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeopleServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Movies.Desktop.PeopleServiceReference.GetAllPeopleResponse Movies.Desktop.PeopleServiceReference.PeopleServiceSoap.GetAllPeople(Movies.Desktop.PeopleServiceReference.GetAllPeopleRequest request) {
            return base.Channel.GetAllPeople(request);
        }
        
        public Movies.Desktop.PeopleServiceReference.Person[] GetAllPeople() {
            Movies.Desktop.PeopleServiceReference.GetAllPeopleRequest inValue = new Movies.Desktop.PeopleServiceReference.GetAllPeopleRequest();
            inValue.Body = new Movies.Desktop.PeopleServiceReference.GetAllPeopleRequestBody();
            Movies.Desktop.PeopleServiceReference.GetAllPeopleResponse retVal = ((Movies.Desktop.PeopleServiceReference.PeopleServiceSoap)(this)).GetAllPeople(inValue);
            return retVal.Body.GetAllPeopleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Movies.Desktop.PeopleServiceReference.GetAllPeopleResponse> Movies.Desktop.PeopleServiceReference.PeopleServiceSoap.GetAllPeopleAsync(Movies.Desktop.PeopleServiceReference.GetAllPeopleRequest request) {
            return base.Channel.GetAllPeopleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Movies.Desktop.PeopleServiceReference.GetAllPeopleResponse> GetAllPeopleAsync() {
            Movies.Desktop.PeopleServiceReference.GetAllPeopleRequest inValue = new Movies.Desktop.PeopleServiceReference.GetAllPeopleRequest();
            inValue.Body = new Movies.Desktop.PeopleServiceReference.GetAllPeopleRequestBody();
            return ((Movies.Desktop.PeopleServiceReference.PeopleServiceSoap)(this)).GetAllPeopleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Movies.Desktop.PeopleServiceReference.GetPersonResponse Movies.Desktop.PeopleServiceReference.PeopleServiceSoap.GetPerson(Movies.Desktop.PeopleServiceReference.GetPersonRequest request) {
            return base.Channel.GetPerson(request);
        }
        
        public Movies.Desktop.PeopleServiceReference.Person GetPerson(System.Guid id) {
            Movies.Desktop.PeopleServiceReference.GetPersonRequest inValue = new Movies.Desktop.PeopleServiceReference.GetPersonRequest();
            inValue.Body = new Movies.Desktop.PeopleServiceReference.GetPersonRequestBody();
            inValue.Body.id = id;
            Movies.Desktop.PeopleServiceReference.GetPersonResponse retVal = ((Movies.Desktop.PeopleServiceReference.PeopleServiceSoap)(this)).GetPerson(inValue);
            return retVal.Body.GetPersonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Movies.Desktop.PeopleServiceReference.GetPersonResponse> Movies.Desktop.PeopleServiceReference.PeopleServiceSoap.GetPersonAsync(Movies.Desktop.PeopleServiceReference.GetPersonRequest request) {
            return base.Channel.GetPersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<Movies.Desktop.PeopleServiceReference.GetPersonResponse> GetPersonAsync(System.Guid id) {
            Movies.Desktop.PeopleServiceReference.GetPersonRequest inValue = new Movies.Desktop.PeopleServiceReference.GetPersonRequest();
            inValue.Body = new Movies.Desktop.PeopleServiceReference.GetPersonRequestBody();
            inValue.Body.id = id;
            return ((Movies.Desktop.PeopleServiceReference.PeopleServiceSoap)(this)).GetPersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Movies.Desktop.PeopleServiceReference.InsertPersonResponse Movies.Desktop.PeopleServiceReference.PeopleServiceSoap.InsertPerson(Movies.Desktop.PeopleServiceReference.InsertPersonRequest request) {
            return base.Channel.InsertPerson(request);
        }
        
        public bool InsertPerson(Movies.Desktop.PeopleServiceReference.Person person) {
            Movies.Desktop.PeopleServiceReference.InsertPersonRequest inValue = new Movies.Desktop.PeopleServiceReference.InsertPersonRequest();
            inValue.Body = new Movies.Desktop.PeopleServiceReference.InsertPersonRequestBody();
            inValue.Body.person = person;
            Movies.Desktop.PeopleServiceReference.InsertPersonResponse retVal = ((Movies.Desktop.PeopleServiceReference.PeopleServiceSoap)(this)).InsertPerson(inValue);
            return retVal.Body.InsertPersonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Movies.Desktop.PeopleServiceReference.InsertPersonResponse> Movies.Desktop.PeopleServiceReference.PeopleServiceSoap.InsertPersonAsync(Movies.Desktop.PeopleServiceReference.InsertPersonRequest request) {
            return base.Channel.InsertPersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<Movies.Desktop.PeopleServiceReference.InsertPersonResponse> InsertPersonAsync(Movies.Desktop.PeopleServiceReference.Person person) {
            Movies.Desktop.PeopleServiceReference.InsertPersonRequest inValue = new Movies.Desktop.PeopleServiceReference.InsertPersonRequest();
            inValue.Body = new Movies.Desktop.PeopleServiceReference.InsertPersonRequestBody();
            inValue.Body.person = person;
            return ((Movies.Desktop.PeopleServiceReference.PeopleServiceSoap)(this)).InsertPersonAsync(inValue);
        }
    }
}
